[package]
edition = "2021"
name = "events"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tauri = {version = "1.4.0", features = []}
pnet = "0.34.0"
net = {path = "../net"}